BCB = [
    "https://vignette.wikia.nocookie.net/marvel-contestofchampions/images/b/bd/Punisher.png/revision/latest?cb=20150702191549",
    "https://vignette.wikia.nocookie.net/marvel-contestofchampions/images/a/af/Full_Energy_Refills.png/revision/latest/top-crop/width/220/height/220?cb=20190505215200",
    "https://vignette.wikia.nocookie.net/marvel-contestofchampions/images/b/b0/Units_icon.png/revision/latest/scale-to-width-down/340?cb=20190505220131",
    "https://vignette.wikia.nocookie.net/marvel-contestofchampions/images/2/2b/Gold_icon.png/revision/latest?cb=20190505220317",
]
FEATUREDS = {
    "abomination": "https://media.discordapp.net/attachments/745608075670585344/768766778691420180/Abomination_featured.png",
    "abominationimmortal": "https://media.discordapp.net/attachments/763066391107862550/777108902248054784/gachachaseprize_256x256_abomination_immortal.png",
    "aegon": "https://media.discordapp.net/attachments/763066391107862550/777109017726025728/gachachaseprize_256x256_aegon.png",
    "agentvenom": "https://media.discordapp.net/attachments/745608075670585344/768766780054569000/Agent_Venom_featured.png",
    "airwalker": "https://media.discordapp.net/attachments/745608075670585344/768766786018476072/air_walker.png",
    "angela": "https://media.discordapp.net/attachments/763066391107862550/777109182271717376/gachachaseprize_256x256_angela.png",
    "annihilus": "https://media.discordapp.net/attachments/745608075670585344/768766792050147348/Annihilus_featured.png",
    "antman": "https://media.discordapp.net/attachments/745608075670585344/768766789223972944/Ant-Man_featured.png",
    "apocalypse": "https://media.discordapp.net/attachments/763066391107862550/777109367719329823/gachachaseprize_256x256_apocalypse.png",
    "aa": "https://media.discordapp.net/attachments/745608075670585344/768766799859941396/Archangel_featured.png",
    "beast": "https://media.discordapp.net/attachments/745608075670585344/768766795615436800/Beast_featured.png",
    "bishop": "https://media.discordapp.net/attachments/745608075670585344/768766827744460840/Bishop_featured.png",
    "blackbolt": "https://media.discordapp.net/attachments/745608075670585344/768766800237953055/Black_Bolt_featured.png",
    "blackpanther": "https://media.discordapp.net/attachments/745608075670585344/768766802116476928/Black_Panther_featured.png",
    "bpcw": "https://media.discordapp.net/attachments/745608075670585344/768766800888070144/Black_Panther_Civil_War_featured.png",
    "blackwidow": "https://media.discordapp.net/attachments/745608075670585344/768766835100614656/Black_Widow_featured.png",
    "bwcv": "https://media.discordapp.net/attachments/745608075670585344/768766851311861790/Black_Widow_Claire_Voyant_featured.png",
    "bwdo": "https://media.discordapp.net/attachments/763066391107862550/777110635451908126/gachachaseprize_256x256_black_widow_timely.png",
    "blade": "https://media.discordapp.net/attachments/745608075670585344/768766856168734730/Blade_featured.png",
    "cable": "https://media.discordapp.net/attachments/763066391107862550/777110835922206720/gachachaseprize_256x256_cable.png",
    "captainamerica": "https://media.discordapp.net/attachments/763066391107862550/777110943120228362/gachachaseprize_256x256_captain_america.png",
    "capiw": "https://media.discordapp.net/attachments/745608075670585344/768766821155209276/Captain_America_Infinity_War_featured.png",
#    "<Science:777119812018896907> capwii": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_capamerica_wwii.png",
#    "cmm": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_captain_marvel_movie.png",
#    "captainmarvel": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_captain_marvel.png",
#    "carnage": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_carnage.png",
#    "Civil Warrior": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_civilwarrior.png",
#    "colossus": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_colossus.png",
#    "corvus": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_corvusglaive.png",
#    "cgr": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_ghost_rider_cosmic.png",
#    "crossbones": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_crossbones.png",
#    "cull": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_cullobsidian.png",
#    "bluecyclops": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_cyclops_90s.png",
#    "cyclops": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_cyclops.png",
#    "daredevilnetflix": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_daredevil_netflix.png",
#    "daredevil": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_daredevil.png",
#    "darkhawk": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_darkhawk.png",
    "deadpool": "https://media.discordapp.net/attachments/745608075670585344/768766846156406784/Deadpool_featured.png",
#    "deadpoolxforce": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_deadpool_xforce.png",
#    "diablo": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_diablo.png",
#    "doom": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_doctordoom.png",
#    "docock": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_doc_ock.png",
#    "drstrange": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_doctor_strange.png",
#    "drvoodoo": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_brother_voodoo.png",
#    "domino": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_domino.png",
    "dormammu": "https://media.discordapp.net/attachments/745608075670585344/768766851378708530/Dormammu_featured.png",
#    "dragonman": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_dragonman.png",
#    "drax": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_drax.png",
#    "ebonymaw": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_ebonymaw.png",
#    "electro": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_electro.png",
#    "elektra": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_elektra.png",
#    "elsa": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_elsabloodstone.png",
#    "emmafrost": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_emmafrost.png",
#    "falcon": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_falcon.png",
#    "gambit": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_gambit.png",
#    "gamora": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_gamora.png",
#    "ghost": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_ghost.png",
#    "ghostrider": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_ghost_rider.png",
#    "goodpool": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_deadpool_gold.png",
#    "greengoblin": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_green_goblin.png",
#    "groot": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_groot.png",
#    "guardian": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_guardian.png",
#    "guillotine": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_guillotine.png",
#    "guillotine2099": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_guillotine_2099.png",
#    "gwenpool": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_gwenpool.png",
#    "havok": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_havok.png",
#    "hawkeye": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_hawkeye.png",
#    "heimdall": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_heimdall.png",
#    "hela": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_hela.png",
#    "hitmonkey": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_hitmonkey.png",
#    "howard": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_howardmech.png",
#    "hulk": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_hulk.png",
#    "gulk": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_hulk_ragnarok.png",
#    "hulkbuster": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_hulkbuster_movie.png",
#    "johnnystorm": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_johnnystorm.png",
#    "hyperion": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_hyperion.png",
#    "iceman": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_iceman.png",
#    "invisiblewoman": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_invisiblewoman.png",
#    "ironfist": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_iron_fist.png",
#    "immortalironfist": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_iron_fist_white.png",
#    "<:Tech:777119812031741973> ironman": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_iron_man.png",
#    "<:Tech:777119812031741973> ironmaninfinitywar": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_ironman_movie.png",
#    "ironpatriot": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_ironpatriot.png",
#    "joefixit": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_joefixit.png",
#    "juggernaut": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_juggernaut.png",
#    "<:Tech:777119812031741973> kang": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_kang.png",
#    "karnak": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_karnak.png",
#    "killmonger": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_killmonger.png",
#    "kinggroot": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_groot_king.png",
#    "kingpin": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_kingpin.png",
#    "korg": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_korg_movie.png",
#    "loki": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_loki.png",
#    "longshot": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_longshot.png",
#    "lukecage": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_luke_cage.png",
#    "modok": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_modok.png",
#    "magik": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_magik.png",
#    "magneto": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_magneto.png",
#    "magnetox": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_magneto_white.png",
#    "manthing": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_manthing.png",
#    "masacre": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_masacre.png",
#    "medusa": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_medusa.png",
#    "mephisto": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_mephisto.png",
#    "mrfantastic": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_mrfantastic.png",
#    "mistersinister": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_mistersinister.png",
#    "mojo": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_mojo.png",
#    "moleman": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_moleman.png",
#    "moonknight": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_moonknight.png",
#    "mordo": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_karl_mordo.png",
#    "morningstar": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_morningstar.png",
#    "msmarvel": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_msmarvel.png",
#    "kamalakhan": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_msmarvel_kamala.png",
#    "mysterio": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_mysterio.png",
#    "namor": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_namor.png",
#    "nebula": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_nebula.png",
#    "nickfury": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_nickfury.png",
#    "nightthrasher": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_nightthrasher.png",
#    "nightcrawler": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_nightcrawler.png",
#    "nova": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_nova.png",
#    "oldmanlogan": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_wolverine_oldman.png",
#    "omegared": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_omegared.png",
#    "phoenix": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_phoenix.png",
#    "platpool": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_deadpool_platinum.png",
#    "professorx": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_professorx.png",
#    "proximamidnight": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_proximamidnight.png",
#    "psylocke": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_psylocke.png",
#    "punisher": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_punisher.png",
#    "punisher2099": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_punisher_2099.png",
#    "quake": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_quake.png",
#    "redgoblin": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_red_goblin.png",
#    "redguardian": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_redguardian.png",
#    "redhulk": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_hulk_red.png",
#    "redskull": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_redskull.png",
#    "rhino": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_rhino.png",
#    "rocket": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_rocket.png",
#    "rogue": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_rogue.png",
#    "ronan": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_ronan.png",
#    "ronin": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_ronin.png",
#    "sabretooth": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_sabretooth.png",
#    "sasquatch": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_sasquatch.png",
#    "scarletwitch": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_scarlet_witch.png",
#    "sentinel": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_sentinel.png",
#    "sentry": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_sentry_current.png",
#    "shehulk": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_shehulk.png",
#    "silversurfer": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_silversurfer.png",
#    "sorcerersupreme": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_drstrange_realm.png",
#    "spidergwen": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_spidergwen.png",
#    "spiderman": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_spider_man.png",
#    "milesmorales": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_spiderman_morales.png",
#    "<:Tech:777119812031741973> spidermanstarkenhanced": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_spiderman_movie.png",
#    "stealthy": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_spiderman_stealth.png",
#    "symbiotespiderman": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_spiderman_black.png",
#    "squirrelgirl": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_squirrelgirl.png",
#    "starlord": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_star_lord.png",
#    "storm": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_storm.png",
#    "stormx": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_storm_realm.png",
#    "superiorironman": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_ironman_superior.png",
#    "symbiotesupreme": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_symbiote_supreme.png",
#    "taskmaster": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_taskmaster.png",
#    "terrax": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_terrax.png",
#    "thanos": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_thanos.png",
#    "champion": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_champion.png",
#    "hood": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_hood.png",
#    "thing": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_thing.png",
#    "thor": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_thor.png",
#    "thorjanfoster": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_thor_janefoster.png",
#    "thorragnarok": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_thor_ragnarok.png",
#    "tigra": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_tigra.png",
#    "ultron": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_ultron.png",
#    "lolultron": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_ultron_prime.png",
#    "unstoppablecolossus": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_colossus_unstoppable.png",
#    "venom": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_venom.png",
#    "venomtheduck": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_venomtheduck.png",
#    "venompool": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_venompool.png",
#    "visionog": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_vision.png",
#    "aarkus": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_vision_timely.png",
#    "visionaou": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_vision_movie.png",
#    "void": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_void_current.png",
#    "vulture": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_vulture_movie.png",
#    "warmachine": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_warmachine.png",
#    "warlock": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_warlock.png",
#    "wasp": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_wasp.png",
#    "wintersoldier": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_winter_soldier.png",
#    "wolverine": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_wolverine.png",
    "weaponx": "https://vignette.wikia.nocookie.net/marvel-contestofchampions/images/b/b7/Wolverine_%28Weapon_X%29_featured.png/revision/latest?cb=20200601191347",
#    "x23": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_x23.png",
#    "yellowjacket": "https://auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_yellowjacket.png"
#     "yondu": "https: // auntm.ai/resources/ui/uigacha/featured/gachachaseprize_256x256_yondu.png"
}

ALIASES = {
    'antman': ['am', 'ant-man', 'ant man'],
    'Civil Warrior': ['cw', 'civilwarrior, civil warrior']
}

FULL_NAMES = {}
for name, aliases in ALIASES.items():
    for alias in aliases:
        FULL_NAMES[alias] = name
