name: Docs
description: Help improve documentation
title: "[Docs] "
labels: [docs, Triage Requested]
body:
  - type: dropdown
    id: type
    attributes:
      label: Documentation Fix Type
      description: Which category does your issue fit under?
      options:
        - Fixes a spelling mistake
        - Documents a new feature that was missed
        - Outlines part of the docs in more detail
        - Removes clusterful text
        - Other
    validations:
      required: true
  - type: input
    id: details
    attributes:
      label: Details
      description: Give some details about your issue
    validations:
      required: true
